import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import Logo from "../public/logo.png"
import Google from "../public/google.svg"
// import uzLeng from "../public/uz-lang.svg"
import ruLeng from "../public/ru-lang.svg"
import usLeng from "../public/us-lang.svg"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-5 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <a href={"/"}><Image src={Logo} alt="logo" className="" /></a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href={"Resume"}
                >
                  Resume
                </a>
              </li>
              <div className="header nav">
                <div className="head-languages">
                  <button className="head-lang lang-us">
                    <span className="text-white font-semibold text-xl mr-1">US</span>
                    <Image src={usLeng} alt="usLang"/>
                  </button>
                  <button className="head-lang lang-ru">
                    <span className="text-white font-semibold text-xl mr-1">RU</span>
                    <Image src={ruLeng} alt="usLang"/>
                  </button>
                  <button className="head-lang lang-uz">
                    <span className="text-white font-semibold text-xl mr-1" >UZ</span>
                    {/* <Image src={uzLeng} alt="UzLang"/> */}
                  </button>
                </div>
              </div>
            </ul>
          </nav>
            <Image src={Google}/>
        </section>
      </main>
    </div>
  );
}
